export const en = {
  lang: 'en',
  nav: {
    links: [
      { label: 'Services', href: '#services' },
      { label: 'Expertise', href: '#expertise' },
      { label: 'News', href: '#actualites' },
      { label: 'Contact', href: '#contact' },
    ],
    cta: 'Book a meeting',
    langSwitch: { label: 'FR', href: '/fr' },
  },
  hero: {
    label: 'You create. We structure. That\'s our expertise.',
    title: ['Your business services partner', 'in Luxembourg and the', 'Greater Region'],
    titleAccent: 'Greater Region',
    subtitle: 'Accounting and administrative services firm based in Mamer, Luxembourg. INEE supports entrepreneurs, self-employed professionals and SMEs worldwide with accounting, VAT returns, tax advisory, company formation, payroll and digital marketing.',
    cta1: 'Book a meeting',
    cta2: 'Our services →',
    credentials: ['Business Services', 'Greater Region & Luxembourg', 'Consulting & Support'],
  },
  services: {
    label: 'Our areas of expertise',
    title: 'Complete solutions',
    titleAccent: 'for your business',
    titleEnd: '',
    subtitle: 'Accounting firm in Luxembourg: bookkeeping, VAT returns, tax optimisation, company formation (SARL, SA), payroll management, HR and digital marketing. INEE, your trusted partner in Mamer.',
    prestations: 'Our services',
    webDemoCaption: 'A glimpse of what we build for you',
    cta: 'Book a meeting',
    learnMore: 'Learn more →',
    categories: [
      {
        num: '01', title: 'Accounting',
        description: 'Full or partial outsourcing of your bookkeeping. Balance sheet, income statement and reporting tailored to your schedule.',
        services: ['Monthly bookkeeping', 'Quarterly bookkeeping', 'Annual bookkeeping', 'Annual accounts review'],
      },
      {
        num: '02', title: 'Tax & Declarations',
        description: 'VAT and tax declarations compliant with Luxembourg law. Full management of your obligations with the Luxembourg Tax Administration.',
        services: ['Monthly VAT return', 'Quarterly VAT return', 'Annual VAT return', 'Corporate income tax return (PM)', 'Personal income tax return (PP)', 'Tax declaration review'],
      },
      {
        num: '03', title: 'Administrative & Secretarial',
        description: 'Complete administrative management for individuals and businesses. Free yourself from administrative tasks and focus on your core activity.',
        services: ['Secretarial services', 'Client invoicing', 'Debt recovery support', 'Annual accounts filing'],
      },
      {
        num: '04', title: 'Legal',
        description: 'Company incorporation (SARL, SA, SAS…), business plan drafting and legal support to structure and launch your business in Luxembourg.',
        services: ['Legal services', 'Full company incorporation', 'Business plan', 'Creation advisory'],
      },
      {
        num: '05', title: 'Training',
        description: 'Training tailored to your level and needs: Luxembourg VAT, basic accounting, customised in-person or online sessions.',
        services: ['VAT training', 'Accounting training', 'Tailored training', 'Online training (e-learning)'],
      },
      {
        num: '06', title: 'Communication & Marketing',
        description: 'Digital presence, social media, video and photo content creation, CRM and event management. Your image, our expertise.',
        services: ['Website creation', 'Digital process — CRM', 'Content creation', 'Marketing', 'Event organisation'],
      },
      {
        num: '07', title: 'HR',
        description: 'Payslip preparation, CCSS declarations, contract management and full HR support for your Luxembourg-based employees.',
        services: ['Payroll management', 'Full HR management (contracts, onboarding, offboarding)'],
      },
      {
        num: '08', title: 'Other Services',
        description: 'Strategic consulting, tax optimisation, financial analysis and bespoke process implementation. Comprehensive support for your growth.',
        services: ['New process implementation', 'Business strategy', 'Personal & corporate tax optimisation', 'Accounting process optimisation', 'Ad-hoc financial analysis', 'Advisory consultation', 'Tax declaration review'],
      },
    ],
  },
  skills: {
    label: 'Our expertise',
    title: 'Why choose',
    titleAccent: 'INEE',
    titleEnd: ' ?',
    arguments: [
      { title: 'Local expertise', text: 'We have in-depth knowledge of Luxembourg\'s legal and tax framework: VAT, CCSS, company law, cross-border taxation.' },
      { title: 'Responsiveness & Availability', text: 'Your dedicated advisor responds within 24 hours. No call centre — you have direct access to your expert.' },
      { title: 'Technology & Innovation', text: '100% digital accounting, online document access, automated tax alerts and real-time reporting.' },
      { title: 'Absolute confidentiality', text: 'Bound by professional secrecy, we handle your data with the strictest confidentiality, in full compliance with GDPR.' },
    ],
    statsTitle: 'By the numbers',
    stats: [
      { value: '15+', label: 'Years of combined experience' },
      { value: '6', label: 'Areas of expertise' },
    ],
    quote: 'INEE means the assurance of expert, caring attention to your business, every day.',
  },
  events: {
    label: 'News & Events',
    title: 'Stay informed about',
    titleAccent: 'the latest developments',
    items: [
      {
        date: 'Free guide — Download now',
        category: 'RESOURCE · FINANCE',
        title: 'Launch your business in Luxembourg without financial pitfalls',
        summary: 'Many entrepreneurs have a great idea but fail through lack of financial preparation. Our "Finance for Entrepreneurs" guide breaks down the essentials: which structure to choose, business plan & forecasts, bank financing (the 5 Cs) and all the funding available in Luxembourg.',
        link: '/inee-finance-for-entrepreneurs-en.pdf',
        cta: 'Download the guide (PDF) →',
        details: [
          { icon: '🏛', text: 'Sole trader, SARL-S, SARL, SA: the decision table' },
          { icon: '📊', text: 'Business plan, cash flow & break-even point' },
          { icon: '🏦', text: 'Bank financing, Microlux, Mutualité & funding' },
        ],
      },
      {
        date: '11 July 2026 — 11:30',
        category: 'TRAINING & WORKSHOP #01',
        title: 'What your accountant doesn\'t tell you!',
        summary: 'Running a business in Luxembourg and not sure why you\'re paying so much? INEE invites you to a practical, jargon-free morning on CCSS, taxes and VAT. Free entry — 30 places available.',
        link: 'https://www.eventbrite.com/e/brunch-atelier-inee-tickets-1990523110206',
        cta: 'Reserve my free spot →',
        details: [
          { icon: '📍', text: '20 rue des Peupliers, L-2328 Luxembourg — Paladuim Pal\'Art' },
          { icon: '🎟', text: 'Free entry · 30 places available' },
          { icon: '📌', text: 'CCSS · Taxes · VAT' },
        ],
      },
    ],
  },
  contact: {
    label: 'Get in touch',
    title: 'Let\'s schedule',
    titleAccent: 'a meeting',
    subtitle: 'A question, a project, a tax emergency? Our team will get back to you within 24 hours.',
    form: {
      title: 'Meeting request',
      firstname: 'First name',
      lastname: 'Last name',
      company: 'Company / Organisation',
      email: 'Professional email',
      phone: 'Phone',
      subject: 'Subject of request…',
      subjects: ['Accounting', 'Tax & Declarations', 'Administrative & Secretarial', 'Legal & Company formation', 'Training', 'Communication & Marketing', 'HR & Payroll', 'Consulting & Strategy', 'Other'],
      message: 'Your message or question',
      consent: 'I consent to the processing of my personal data in accordance with the',
      privacyLink: 'privacy policy',
      privacyHref: '/privacy-policy',
      cguLink: 'terms of use',
      cguHref: '/terms-of-use',
      submit: 'Send my request',
      sending: 'Sending…',
      successTitle: 'Request sent',
      successText: 'We will get back to you within 24 business hours.\nThank you for your trust.',
      newRequest: 'New request',
      error: 'An error occurred. Please try again or contact us directly at contact@inee.lu',
    },
    info: {
      addressLabel: 'Address — Open navigation',
      addressValue: '37, Rue du Baumbusch\n8213 Mamer — Luxembourg',
      emailLabel: 'Email — Write a message',
      emailValue: 'contact@inee.lu',
      phoneLabel: 'Phone & WhatsApp',
      phoneValue: '+352 661 185 049',
      vatLabel: 'VAT No.',
      vatValue: 'LU36332830',
      hoursLabel: 'Office hours',
      hoursValue: 'Mon–Fri, 8:30am–6:00pm',
      footer: 'Business services company\nbased in Mamer, Grand Duchy of Luxembourg',
    },
    quote: 'Available Monday to Friday, 8:30am to 6:00pm, to answer all your questions.',
  },
  footer: {
    tagline: 'Accounting firm in Mamer, Luxembourg. Bookkeeping, VAT returns, tax advisory, company formation, payroll & HR, strategic consulting and digital marketing.',
    address1: '37, Rue du Baumbusch — 8213 Mamer',
    address2: 'Grand Duchy of Luxembourg',
    vat: 'VAT: LU36332830',
    servicesTitle: 'Our services',
    services: ['Accounting', 'Tax & Declarations', 'Administrative', 'Legal & Company formation', 'HR & Payroll', 'Training', 'Communication & Marketing', 'Consulting & Strategy'],
    companyTitle: 'Company',
    company: ['Our team', 'Our values', 'Tax news', 'Events', 'Careers', 'Partners'],
    contactTitle: 'Contact',
    hours: 'Mon–Fri · 8:30am–6:00pm',
    ctaBtn: 'Book a meeting',
    copyright: '© 2026 INEE S.à r.l.-S. All rights reserved.',
    madeBy: 'Website by JDIGITAL',
    legal: [
      { label: 'Privacy Policy', href: '/privacy-policy' },
      { label: 'Terms of Use', href: '/terms-of-use' },
      { label: 'Legal Notice', href: '/legal-notice' },
      { label: 'T&Cs', href: '/terms-and-conditions' },
    ],
  },
}
