export const fr = {
  lang: 'fr',
  nav: {
    links: [
      { label: 'Services', href: '#services' },
      { label: 'Expertise', href: '#expertise' },
      { label: 'Actualités', href: '#actualites' },
      { label: 'Contact', href: '#contact' },
    ],
    cta: 'Prendre rendez-vous',
    langSwitch: { label: 'EN', href: '/en' },
  },
  hero: {
    label: 'Vous créez. On structure. C\'est notre expertise.',
    title: ['Votre partenaire de services', 'aux entreprises au Luxembourg et', 'les trois frontières'],
    titleAccent: 'les trois frontières',
    subtitle: 'Cabinet de gestion et administratif basé à Mamer, Luxembourg. INEE accompagne les entrepreneurs, indépendants et PME du Luxembourg et de la Grande Région dans leur comptabilité, fiscalité, gestion RH, création d\'entreprise et communication digitale.',
    cta1: 'Prendre rendez-vous',
    cta2: 'Nos services →',
    credentials: ['Services aux entreprises', 'Grande Région & Luxembourg', 'Conseil & Accompagnement'],
  },
  services: {
    label: 'Nos domaines d\'expertise',
    title: 'Des solutions',
    titleAccent: 'complètes',
    titleEnd: 'pour votre entreprise',
    subtitle: 'Cabinet de gestion au Luxembourg : tenue comptable, déclarations TVA, optimisation fiscale, création de SARL, gestion des salaires, RH et marketing digital. INEE, votre partenaire global à Mamer.',
    prestations: 'Nos prestations',
    webDemoCaption: 'Un aperçu de ce que nous construisons pour vous',
    cta: 'Prendre rendez-vous',
    learnMore: 'En savoir plus →',
    categories: [
      {
        num: '01', title: 'Comptabilité',
        description: 'Externalisation complète ou partielle de votre comptabilité. Bilan, compte de résultat et reporting adapté à votre rythme.',
        services: ['Tenue comptable mensuelle', 'Tenue comptable trimestrielle', 'Tenue comptable annuelle', 'Revue des comptes annuels'],
      },
      {
        num: '02', title: 'Fiscalité',
        description: 'Déclarations TVA et fiscales conformes au droit luxembourgeois. Gestion complète de vos obligations envers l\'Administration fiscale luxembourgeoise.',
        services: ['Déclaration TVA mensuelle', 'Déclaration TVA trimestrielle', 'Déclaration TVA annuelle', 'Déclaration fiscale société (PM)', 'Déclaration fiscale personne physique (PP)', 'Revue déclaration fiscale'],
      },
      {
        num: '03', title: 'Administratif',
        description: 'Gestion administrative complète pour particuliers et entreprises. Libérez-vous des tâches administratives et concentrez-vous sur votre activité.',
        services: ['Secrétariat', 'Facturation client', 'Accompagnement recouvrement de dettes', 'Dépôt des comptes annuels'],
      },
      {
        num: '04', title: 'Legal',
        description: 'Création de sociétés (SARL, SA, SAS…), rédaction de business plan et accompagnement juridique pour structurer et lancer votre activité au Luxembourg.',
        services: ['Prestations légales', 'Constitution de société complète', 'Business plan', 'Accompagnement création (conseil)'],
      },
      {
        num: '05', title: 'Formation',
        description: 'Formations adaptées à votre niveau et vos besoins : TVA luxembourgeoise, comptabilité de base, sessions sur mesure en présentiel ou en ligne.',
        services: ['Formation TVA', 'Formation comptable', 'Formation sur mesure', 'Formation en ligne (e-learning)'],
      },
      {
        num: '06', title: 'Communication & Marketing',
        description: 'Présence digitale, réseaux sociaux, création de contenu vidéo et photo, CRM et organisation d\'événements. Votre image, notre expertise.',
        services: ['Création de site internet', 'Process digital — CRM', 'Création de contenu', 'Marketing', 'Organisation d\'événement'],
      },
      {
        num: '07', title: 'RH',
        description: 'Calcul des fiches de salaire, déclarations CCSS, gestion des contrats et accompagnement RH complet pour vos collaborateurs luxembourgeois.',
        services: ['Gestion des salaires', 'Gestion RH complète (contrats, onboarding, offboarding)'],
      },
      {
        num: '08', title: 'Autres prestations',
        description: 'Conseil stratégique, optimisation fiscale, analyse financière et mise en place de process sur mesure. Un accompagnement global pour votre croissance.',
        services: ['Mise en place de nouveaux process', 'Stratégie d\'entreprise', 'Optimisation fiscale PP & PM', 'Optimisation processus comptables', 'Analyse financière ponctuelle', 'Consultation conseil', 'Revue déclaration fiscale'],
      },
    ],
  },
  skills: {
    label: 'Notre expertise',
    title: 'Pourquoi choisir',
    titleAccent: 'INEE',
    titleEnd: ' ?',
    arguments: [
      { title: 'Expertise locale', text: 'Nous connaissons parfaitement le cadre légal et fiscal luxembourgeois : TVA, CCSS, droit des sociétés, fiscalité transfrontalière.' },
      { title: 'Réactivité & Disponibilité', text: 'Votre conseiller dédié répond sous 24h. Pas de standard téléphonique, vous avez un contact direct avec votre expert.' },
      { title: 'Technologie & Modernité', text: 'Comptabilité 100% digitale, accès à vos documents en ligne, alertes fiscales automatisées et reporting en temps réel.' },
      { title: 'Confidentialité absolue', text: 'Soumis au secret professionnel, nous traitons vos données avec la plus stricte confidentialité, conformément au RGPD.' },
    ],
    statsTitle: 'En chiffres',
    stats: [
      { value: '15+', label: 'Cumulé d\'ancienneté' },
      { value: '6', label: 'Domaines d\'expertise' },
    ],
    quote: 'INEE, c\'est l\'assurance d\'un regard expert et bienveillant sur votre activité, chaque jour.',
  },
  events: {
    label: 'Actualités & Événements',
    title: 'Restez informé des',
    titleAccent: 'nouveautés fiscales',
    items: [
      {
        date: 'Guide gratuit — À télécharger',
        category: 'RESSOURCE · FINANCE',
        title: 'Se lancer au Luxembourg sans se planter financièrement',
        summary: 'Beaucoup d\'entrepreneurs ont une super idée mais échouent par manque de préparation financière. Notre guide « Finance pour Entrepreneurs » décrypte l\'essentiel : quelle structure choisir, business plan & prévisionnel, financement bancaire (les 5C) et toutes les aides disponibles au Luxembourg.',
        link: '/inee-finance-entrepreneurs.pdf',
        cta: 'Télécharger le guide (PDF) →',
        details: [
          { icon: '🏛', text: 'Indépendant, SARL-S, SARL, SA : le tableau de décision' },
          { icon: '📊', text: 'Business plan, trésorerie & seuil de rentabilité' },
          { icon: '🏦', text: 'Financement bancaire, Microlux, Mutualité & aides' },
        ],
      },
      {
        date: '11 Juillet 2026 — 11h30',
        category: 'FORMATION & ATELIER #01',
        title: 'Ce que ton comptable ne te dit pas !',
        summary: 'Tu gères une activité au Luxembourg et tu paies sans vraiment comprendre pourquoi ? INEE t\'invite à une matinée concrète et sans jargon sur la CCSS, les impôts et la TVA. Entrée gratuite — 30 places disponibles.',
        link: 'https://www.eventbrite.com/e/brunch-atelier-inee-tickets-1990523110206',
        cta: 'Réserver ma place gratuite →',
        details: [
          { icon: '📍', text: "20 rue des Peupliers, L-2328 Luxembourg — Paladuim Pal'Art" },
          { icon: '🎟', text: 'Entrée gratuite · 30 places disponibles' },
          { icon: '📌', text: 'CCSS · Impôts · TVA' },
        ],
      },
    ],
  },
  contact: {
    label: 'Nous contacter',
    title: 'Prenons',
    titleAccent: 'rendez-vous',
    subtitle: 'Une question, un projet, une urgence comptable ? Notre équipe vous répond sous 24h.',
    form: {
      title: 'Demande de rendez-vous',
      firstname: 'Prénom',
      lastname: 'Nom',
      company: 'Société / Organisation',
      email: 'Email professionnel',
      phone: 'Téléphone',
      subject: 'Objet de la demande…',
      subjects: ['Comptabilité', 'Fiscalité & Déclarations', 'Administratif & Secrétariat', 'Legal & Création d\'entreprise', 'Formation', 'Communication & Marketing', 'RH & Gestion des salaires', 'Conseil & Stratégie', 'Autre'],
      message: 'Votre message ou question',
      consent: 'Je consens au traitement de mes données personnelles conformément à la',
      privacyLink: 'politique de confidentialité',
      privacyHref: '/confidentialite',
      cguLink: 'CGU',
      cguHref: '/cgu',
      submit: 'Envoyer ma demande',
      sending: 'Envoi en cours…',
      successTitle: 'Demande envoyée',
      successText: 'Nous vous recontacterons dans les 24h ouvrables.\nMerci de votre confiance.',
      newRequest: 'Nouvelle demande',
      error: 'Une erreur s\'est produite. Veuillez réessayer ou nous contacter directement à contact@inee.lu',
    },
    info: {
      addressLabel: 'Adresse — Ouvrir la navigation',
      addressValue: '37, Rue du Baumbusch\n8213 Mamer — Luxembourg',
      emailLabel: 'Email — Écrire un message',
      emailValue: 'contact@inee.lu',
      phoneLabel: 'Téléphone & WhatsApp',
      phoneValue: '+352 661 185 049',
      vatLabel: 'N° TVA',
      vatValue: 'LU36332830',
      hoursLabel: 'Horaires',
      hoursValue: 'Lun–Ven, 8h30–18h00',
      footer: 'Société de services aux entreprises\nbasée à Mamer, Grand-Duché de Luxembourg',
    },
    quote: 'Disponibles du lundi au vendredi, de 8h30 à 18h00, pour répondre à toutes vos questions.',
  },
  footer: {
    tagline: 'Cabinet de gestion à Mamer, Luxembourg. Comptabilité, déclaration TVA, fiscalité, création de société, gestion RH & salaires, conseil stratégique et communication digitale.',
    address1: '37, Rue du Baumbusch — 8213 Mamer',
    address2: 'Grand-Duché de Luxembourg',
    vat: 'TVA : LU36332830',
    servicesTitle: 'Nos services',
    services: ['Comptabilité', 'Fiscalité & Déclarations', 'Administratif', 'Legal & Création d\'entreprise', 'RH & Salaires', 'Formation', 'Communication & Marketing', 'Conseil & Stratégie'],
    companyTitle: 'Cabinet',
    company: ['Notre équipe', 'Nos valeurs', 'Actualités fiscales', 'Événements', 'Carrières', 'Partenaires'],
    contactTitle: 'Contact',
    hours: 'Lun–Ven · 8h30–18h00',
    ctaBtn: 'Prendre rendez-vous',
    copyright: '© 2026 INEE S.à r.l.-S. Tous droits réservés.',
    legal: [
      { label: 'Politique de confidentialité', href: '/confidentialite' },
      { label: 'CGU', href: '/cgu' },
      { label: 'Mentions légales', href: '/mentions-legales' },
      { label: 'CGV', href: '/cgv' },
    ],
  },
}

export type SiteContent = typeof fr
